///macros()

#macro PLATFORM_DESKTOP		0
#macro PLATFORM_MOBILE		1
#macro PLATFORM_CONSOLE		2


#macro VOID		0
#macro SOLID	1
#macro PLATFORM 2
#macro DEATH	3


//camera
#macro CAMERA_RESET			0
#macro SCREEN_SHAKE_TIME	1

//attack
#macro CAN_ATTACK		0
#macro PLAYERSHOTTIMER	3

//frog
#macro INHALE			1
#macro HURT				2

//bug
#macro KNOCKEDBACK		3

//chest
#macro OPEN				0

//arrow
#macro LAYER_CHANGE		0


//Generator
#macro G_9SLICE_UNKNOWN			-999
#macro G_9SLICE_NONE			-1
#macro G_9SLICE_TOPLEFT			0
#macro G_9SLICE_TOPMID			1
#macro G_9SLICE_TOPRIGHT		2
#macro G_9SLICE_MIDLEFT			3
#macro G_9SLICE_CENTER			4
#macro G_9SLICE_MIDRIGHT		5
#macro G_9SLICE_BOTTOMLEFT		6
#macro G_9SLICE_BOTTOMMID		7
#macro G_9SLICE_BOTTOMRIGHT		8
#macro G_9SLICE_TOPHANGER		18
#macro G_9SLICE_BOTTOMUPJUT		19
#macro G_9SLICE_SINGLEISLAND	20

//Inside
#macro G_9SLICE_INSIDE_BOTTOMLEFT 9
#macro G_9SLICE_INSIDE_BOTTOMRIGHT 10
#macro G_9SLICE_INSIDE_TOPLEFT 11
#macro G_9SLICE_INSIDE_TOPRIGHT 12

//Platform
#macro G_PLATFORM_LEFT 13
#macro G_PLATFORM_MID 14 
#macro G_PLATFORM_RIGHT 15
#macro G_PLATFORM_WALLLEFT 16
#macro G_PLATFORM_WALLRIGHT 17
